---
- hosts: nodes
  connection: local
  serial: 1  # task를 1개씩 실행하여 진행할 수 있도록 하는 설정 
  gather_facts: no

  tasks:
  - command: /usr/bin/ssh-keyscan -t ecdsa {{ ansible_host }}   # /etc/ansible/hosts
    register: keyscan

  - lineinfile:
      name=~/.ssh/known_hosts
      create=yes
      line={{ item }}
    with_items:
      - "{{ keyscan.stdout_lines }}"